on: workflow_dispatch

jobs:
  cache_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: test2.txt
          key: test-85a4ade610cdeca342a27293869804d347d914fe-2023-05-15-15-23
          restore-keys: |
            test-
      - uses: actions/cache@v3
        with:
          path: test3.txt
          key: test-85a4ade610cdeca342a27293869804d347d914fe-2023-05-15-15-23
          restore-keys: |
            test-
      - uses: actions/cache@v3.2.0
        with:
          path: test32.txt
          key: test-85a4ade610cdeca342a27293869804d347d914fe-2023-05-15-15-23
          restore-keys: |
            test-
      - uses: actions/cache@v3.0.0
        with:
          path: test30.txt
          key: test-85a4ade610cdeca342a27293869804d347d914fe-2023-05-15-15-23
          restore-keys: |
            test-
      - uses: actions/cache@v3.0.11
        with:
          path: test3011.txt
          key: test-85a4ade610cdeca342a27293869804d347d914fe-2023-05-15-15-23
          restore-keys: |
            test-
