on: workflow_dispatch

jobs:
  cache_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123 > test.txt
      - uses: actions/cache/save@v3
        with:
          path: test.txt
          key: test-${{ github.sha }}-$(date +"%Y-%m-%d-%H-%M")
      - uses: actions/cache/restore@v3
        with:
          path: test2.txt
          key: test-${{ github.sha }}
          restore-keys: |
            test-
      - run: cat test2.txt
